# @file sonar-project.properties
# @description Configurações para análise de código com SonarQube para o projeto "tinas-career-pipeline".
#
# @author Tina de Almeida
# @date Abril de 2026
# @version 1.0.0

# Identificação do projeto no SonarCloud
sonar.projectKey=tinalmeid_python-tinas-career-pipeline
# 🏢 A organização no SonarCloud
sonar.organization=tinalmeid
# 📛 O nome que você verá no dashboard (pode ser sem o prefixo)
sonar.projectName=tinalmeid_python-tinas-career-pipeline
sonar.projectVersion=1.0

# 📂 Onde o código está (raiz)
sonar.sources=.
sonar.exclusions=**/venv/**,**/__pycache__/**,**/.pytest_cache/**


# 🐍 Versão do Python
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

# Encoding
sonar.sourceEncoding=UTF-8

# @Fim do arquivo sonar-project.properties
