# @file sonar-project.properties
# @description Configurações para análise de código com SonarQube para o projeto "tinas-career-pipeline".
#
# @author Tina de Almeida
# @date Abril de 2026
# @version 1.0.0

# sonar-project.properties
sonar.projectKey=tinalmeid_python-tinas-career-pipeline
sonar.organization=tinalmeid
sonar.projectName=python-tinas-career-pipeline
sonar.projectVersion=1.0

# Caminho do código fonte
sonar.sources=.
sonar.exclusions=**/tests/**,**/test_*.py,**/venv/**,**/__pycache__/**,**/.pytest_cache/**

# Python config
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

# Encoding
sonar.sourceEncoding=UTF-8

# @Fim do arquivo sonar-project.properties
